# SEO
title: EPSI-WIS Alumni
email: contact@epsi-wis-alumni.fr
description: >- 
  Le site officiel des anciens étudiants de l'EPSI et de WIS. Retrouvez toutes 
  les informations sur les événements, les offres d'emploi et les actualités de 
  l'association.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://epsi-wis-alumni.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  d9beuD

author:
  name: Vincent BATHELIER
  url: https://d9beud.com

timezone: Europe/Paris

# Build settings
postcss:
  cache: false

kramdown:
  input: GFM

pagination:
  enabled: true
  per_page: 10
  permalink: /:num.html
  title: ':title (:num of :max)'
  limit: 0
  trail:
    before: 2
    after: 2
  collection: posts
  sort_reverse: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: 
        name: Vincent BATHELIER
        avatar: /assets/img/vbathelier.webp
        bio: >-
          I am a web developer and I love to share my knowledge with the community.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
